### ISSUE TITLE
Chart Title Does not update

### ISSUE THREAD

**Issue by Descent098** [bufferhead-code/onthisday#2]
It looks like the chart titles don't update when you re-render a different countries data (third arrow is still austria when it should be Canada):

![image](https://github.com/bufferhead-code/onthisday/assets/22761705/411966d0-04ab-4521-a3dc-cef7293e7e39)

Not a big deal, but thought I would mention it 😄! Great project, really interesting premise!

**Comment by asl97** [comment]
Seem you didn't notice, it's not just the title that didn't update, the bottom text data also didn't update, as in it's for austria instead of canada.

If you open up austria again, you see the top part of the data match the bottom.

![onthisday bufferhead com](https://github.com/bufferhead-code/onthisday/assets/4752645/605b9abe-4dc7-4d41-9f13-76fd6858edea)

____

While the way the project is setup is interesting, I do wonder if a bunch of json files would be better.

Since it current use a bunch of split database files, updates probably wouldn't play nicely with git.

Whereas a json file is just text, if the project just want to get the data for a specific day for all years in the most efficient way, that's just 365 files, 1 for each day per country.

And instead of regular json files, it could be jsonlines files, one line per year, which would mean updates is just appending 1 line to 1 file for each country, without needing to read, parse, update and dump/stringify back to json.

**Comment by bufferhead-code** [comment]
both issues should be fixed now. 

Regarding the JSON files, the project is here to showcase the behavior of SQL.js-httpvfs. I don't like talking about things without using them, and this is a project I had in my head for a while, so that's why I chose it. 

Sure, you could put all the data for one day for all countries in one JSON file. You could also split it per day per country, but then it would be over 70,000 JSON files.
